name:                SCRIPTAnalyser
version:             0.1.0.0
github:              "https://github.com/RKlompUU/SCRIPTAnalyser"
license:             BSD3
author:              "Rick Klomp"
maintainer:          "r.klomp@cs.stir.ac.uk"
copyright:           "2018 Rick Klomp"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at https://github.com/RKlompUU/SCRIPTAnalyser

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  SCRIPTAnalyser-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - SCRIPTAnalyser

